<script setup>
import { Link } from '@inertiajs/vue3';
const items = [
 { area:'Client management', task:'Client intake, onboarding & reminders', current:'Copy details between email, sheets and project board; manually send welcome and reminder messages.', effort:'35 min / new client', automation:'CRM form → create client/project checklist → send templated welcome and due-date reminders.', tool:'HubSpot CRM / Laravel + email', cost:'Free CRM tier; paid email/workflow limits may apply.', save:20 },
 { area:'Content creation', task:'Brief-to-caption first draft', current:'Read the brief, research topics, draft captions, then rewrite for each platform.', effort:'90 min / campaign', automation:'Reusable prompt generates platform drafts, hashtags and a review checklist from an approved brief.', tool:'ChatGPT / Gemini + Google Docs', cost:'Free tiers; paid AI plan optional.', save:55 },
 { area:'Social media', task:'Post scheduling & publishing calendar', current:'Copy approved posts into each social platform and track dates in a spreadsheet.', effort:'60 min / week', automation:'One calendar queues approved posts and publishes to connected channels.', tool:'Buffer', cost:'Free: up to 3 channels and 10 queued posts per channel; Essentials is about $5/channel/month with annual billing.', save:40 },
 { area:'Graphic design', task:'Resize campaign artwork for channels', current:'Open each design, resize canvas, adjust crop/text and export variants one by one.', effort:'45 min / campaign', automation:'Use brand templates and batch resize; keep a human design approval step.', tool:'Canva templates / Bulk Create', cost:'Free basics; some resize/brand features require Pro.', save:30 },
 { area:'Video editing', task:'Create captions and short-form cuts', current:'Manually transcribe long videos, find clips, add captions and export versions.', effort:'120 min / video', automation:'Transcribe, detect candidate highlights, auto-caption and export drafts for editor review.', tool:'CapCut / Descript', cost:'Free features; premium AI/export limits may be paid.', save:60 },
 { area:'Digital marketing', task:'Campaign launch QA & lead routing', current:'Check targeting, links, budgets and form responses manually; forward leads to a person.', effort:'50 min / campaign', automation:'Launch checklist plus form-triggered assignment and notification, with exception alerts.', tool:'Meta/Google native rules + Zapier', cost:'Native checks free; Zapier Free has 100 tasks/month; Professional starts around $19.99/month for multi-step workflows.', save:30 },
 { area:'Reporting', task:'Weekly KPI report compilation', current:'Export channel data, copy figures into a spreadsheet, calculate changes and write a summary.', effort:'120 min / week', automation:'Connect data sources to a dashboard and generate a draft narrative with source links.', tool:'Looker Studio / Sheets', cost:'Free for basic reporting; connectors or BI tiers may be paid.', save:75 },
 { area:'Lead management', task:'Lead capture, qualification & follow-up draft', current:'Read inquiries, compare budget/urgency, decide priority, log details and write first response.', effort:'12 min / lead', automation:'Validate intake, score against transparent rules, classify Hot/Warm/Cold and prepare a reviewable reply.', tool:'This Laravel + Vue prototype; optional CRM', cost:'Prototype uses existing project stack; self-hosting/hosting costs may apply.', save:7 },
 { area:'Intern management', task:'Intern task assignment & weekly check-in', current:'Send onboarding links, repeat instructions, chase updates and summarize progress manually.', effort:'30 min / intern / week', automation:'Template onboarding checklist, assign recurring tasks, send check-in form and flag overdue work.', tool:'Trello / Notion + email automation', cost:'Free tiers; team permissions/automation limits can require paid plan.', save:18 },
 { area:'Team communication', task:'Meeting notes, decisions & action items', current:'Someone types notes, identifies owners and manually follows up on deadlines.', effort:'45 min / meeting', automation:'Transcribe with consent, summarize decisions, extract owners/dates and post a reviewed task list.', tool:'Google Meet notes / Microsoft Teams + task board', cost:'Basic tools may be included; AI transcription depends on workspace plan.', save:25 },
];
const total = items.reduce((n, x) => n + x.save, 0);
</script>
<template>
<div class="app report-app"><aside class="sidebar"><div class="logo-mark">B</div><div class="logo">Biswas <span>IT Firm</span><small>Smart business automation</small></div><nav class="side-nav"><Link href="/leads#dashboard"><i>⌂</i>Dashboard</Link><Link href="/leads#lead-list"><i>♧</i>Leads</Link><Link href="/leads#lead-intake"><i>＋</i>Add Lead</Link><Link href="/leads#lead-list"><i>◉</i>Contacts</Link><Link href="/leads#settings"><i>⚙</i>Settings</Link><Link href="/automation" class="active"><i>✦</i>Automation Hunt</Link></nav><div class="sidebar-profile"><span class="avatar">B</span><div><strong>Biswas IT Firm</strong><small>Agency workspace</small></div></div></aside>
<main><header><div><label>TASK 01 · AGENCY AUTOMATION HUNT</label><h1>10 repetitive tasks to automate</h1><p>Working estimates for a small agency. Validate against a one-week time log before rollout.</p></div><Link class="primary-link" href="/leads">Open working prototype →</Link></header>
<div class="cards"><div><small>Problems mapped</small><b>10</b><em>Across agency workflows</em></div><div><small>Potential time saved</small><b>{{total}}m</b><em>Per one unit of each task listed</em></div><div><small>Selected prototype</small><b>Lead flow</b><em>Capture → score → draft reply</em></div><div><small>Starting cost</small><b>$0</b><em>Free tiers / existing stack</em></div></div>
<section class="panel report-intro"><h2>How to read these estimates</h2><p>Times are planning estimates, not measured Biswas IT Firm data. “Save” is an estimated reduction per unit after setup, excluding human review. Frequency differs by task, so the  {{total}} minutes are not a weekly total. Tool plans and limits vary by region and can change; confirm before purchase.</p></section>
<section class="report-list"><article v-for="(item,i) in items" :key="item.task" class="panel report-card"><div class="report-title"><span class="number">{{String(i+1).padStart(2,'0')}}</span><div><label>{{item.area}}</label><h2>{{item.task}}</h2></div><span class="pill warm">Save ~{{item.save}}m</span></div><div class="report-grid"><div><h3>Current workflow</h3><p>{{item.current}}</p></div><div><h3>Proposed automation</h3><p>{{item.automation}}</p></div><div><h3>Manual effort</h3><p>{{item.effort}}</p></div><div><h3>Tool & cost</h3><p><strong>{{item.tool}}</strong><br>{{item.cost}}</p></div></div></article></section>
<section class="panel chosen"><div><label>FINAL CHALLENGE · BUILT PROTOTYPE</label><h2>Lead qualification and follow-up draft</h2><p>Use the working lead intake to save a lead, calculate a transparent score from budget, urgency, service and referral source, assign priority, and generate an editable human-review reply. Search, priority filtering, dashboard metrics and lead details are included.</p><p><strong>Why this one:</strong> it reduces response delay at the point where a missed or late lead can cost revenue, and can be demonstrated without paid AI/API access.</p></div><Link class="primary-link" href="/leads">Try the prototype →</Link></section>
<section class="panel next"><h2>Future improvement</h2><p>Measure actual baseline time and inquiry volume; add follow-up status and due dates; connect a real lead form and email provider; add role-based access and audit history; validate scoring with won/lost outcomes; then test AI reply suggestions against staff-approved templates. Keep sending behind human approval.</p></section>
<footer>Tool tiers checked September 2026. <a href="https://www.hubspot.com/pricing/crm" target="_blank" rel="noreferrer">HubSpot</a> · <a href="https://buffer.com/pricing" target="_blank" rel="noreferrer">Buffer</a> · <a href="https://www.canva.com/pricing/" target="_blank" rel="noreferrer">Canva</a> · <a href="https://zapier.com/pricing" target="_blank" rel="noreferrer">Zapier</a></footer>
</main></div>
</template>
